# Generated by Django 6.0.1 on 2026-01-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Eduction', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='')),
                ('Document', models.FileField(upload_to='')),
                ('Audio', models.FileField(upload_to='')),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
