# Generated by Django 6.0.1 on 2026-01-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='video',
            new_name='Video',
        ),
    ]
