# Generated by Django 6.0.1 on 2026-01-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_video_student_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Contact',
            field=models.BigIntegerField(),
        ),
    ]
