# Generated by Django 6.0.1 on 2026-01-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Audio',
            field=models.FileField(upload_to='audios'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Document',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
