# Generated by Django 6.0.1 on 2026-01-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_audio_alter_student_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Eduction',
            new_name='Education',
        ),
    ]
